apiVersion: v1
kind: Service
metadata:
  name: expense-tracker-service
spec:
  selector:
    app: expense-tracker
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110